# Generated by Django 5.2.3 on 2025-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='pairing_code',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
