# Generated by Django 5.2.3 on 2025-06-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0002_alter_couple_pairing_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='pairing_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
