# Generated by Django 5.2.3 on 2025-06-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0003_alter_couple_pairing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='combined_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couple',
            name='name',
            field=models.CharField(default='New Couple', max_length=100),
        ),
    ]
