# Generated by Django 5.2.3 on 2025-06-30 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0004_couple_combined_points_couple_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couple',
            name='last_activity_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couple',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
