# Generated by Django 5.2.3 on 2025-06-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=20)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('Couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple.couple')),
            ],
        ),
    ]
