# Generated by Django 5.2.3 on 2025-06-30 14:05

import django.db.models.deletion
from django.db import migrations, models

def create_initial_achievements(apps, schema_editor):
    Achievement = apps.get_model('app_name', 'Achievement')
    
    achievements = [
        {
            'name': 'First Step Together',
            'description': 'Complete your first task as a couple',
            'icon': '👫',
            'xp_reward': 20,
            'unlock_rules': {'task_count': 1}
        },
        {
            'name': 'Task Masters',
            'description': 'Complete 10 tasks together',
            'icon': '🏆',
            'xp_reward': 50,
            'unlock_rules': {'task_count': 10}
        },
        {
            'name': 'Romantic Duo',
            'description': 'Complete 5 romance-themed tasks',
            'icon': '💖',
            'xp_reward': 30,
            'unlock_rules': {'category_tasks': 5, 'category': 'ROMANCE'}
        },
        {
            'name': 'Hard Workers',
            'description': 'Complete 3 hard difficulty tasks',
            'icon': '💪',
            'xp_reward': 40,
            'unlock_rules': {'difficulty_tasks': 3, 'difficulty': 'HARD'}
        },
        {
            'name': 'Weekly Streak',
            'description': 'Maintain a 7-day activity streak',
            'icon': '🔥',
            'xp_reward': 100,
            'unlock_rules': {'streak_days': 7}
        }
    ]
    
    for ach in achievements:
        Achievement.objects.create(**ach)

class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0005_couple_current_streak_couple_last_activity_date_and_more'),
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoupleAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.achievement')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple.couple')),
            ],
            options={
                'unique_together': {('couple', 'achievement')},
            },
        ),
    ]
