# Generated by Django 5.2.3 on 2025-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_achievement_coupleachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='unlock_rules',
            field=models.JSONField(blank=True, default=dict, help_text='\n    JSON structure defining unlock condition. Examples:\n    - First task: {"task_count": 1}\n    - 3-day streak: {"streak_days": 3}\n    - Complete 5 hard task: {"hard_task": 5}                         \n    '),
        ),
    ]
